### ISSUE TITLE
Lens effect only applying to bottom portion of map

### ISSUE THREAD

**Issue by vttale** [astog/MoreLenses#11]
Encountered a weird situation where the lens effects were not applying to all hexes in the normal view.  The unapplied versus applied difference was a very clear horizontal split across the map.  It didn't occur to me until now to check if it was a fully edge-to-edge line, however.

I had a ridiculous game going on a Huge Pangea map where things just got out of hand. (Background on that available on request, but I don't think it's really germane for the issue report.)  What might be germane is that I eventually ended up with so many cities spammed that my civ, Russia, ran out of names in the Russian list and started naming new ones after American cities.  I owned like 80% of the land on the map, and the majority of it was unimproved hexes.  

I could probably get you a save game if it helps.  I was playing with CQUI and all the current DLC enabled.

**Comment by astog** [comment]
Save game helps, also can you upload a screenshot of what it looks like?

**Comment by vttale** [comment]
![20161231212240_1](https://cloud.githubusercontent.com/assets/8977507/21579997/0e56ccd0-cfa0-11e6-9414-3906b6da7de4.jpg)

**Comment by vttale** [comment]
[PETER 417 2216 AD LensBug.zip](https://github.com/astog/MoreLenses/files/679906/PETER.417.2216.AD.LensBug.zip)

**Comment by astog** [comment]
@vttale Do other lenses work? Like city overlap 9 or the builder lens?

**Comment by astog** [comment]
Ok, this bug mainly occurs due to the engine limitation on how many tiles can be colored. Commit c3e2149 has an option to only highlight plots within borders than is a pseudo-fix for this.
