### ISSUE TITLE
Builder Lens enhancements

### ISSUE THREAD

**Issue by vttale** [astog/MoreLenses#13]
I've currently got a ridiculous game going for the Trans-Siberian Achievement and it's giving me a lot of interaction with the builder lens, because I seem to be fundamentally incapable of not developing my lands while waiting for trade routes to run.  Here are some observations.

"Generic Tile" gets applied to all of flat plains, flat snow, and flat desert.  When deciding whether to move a builder to a tile, it is hard to distinguish the first case, which can get a farm or forest, from the latter two, which can't have anything done to them.  The same is sort of true of water with no resources, but at least you can readily tell that's what the hex is.  I think my personal preference would be in all of those cases to just have no lens tint applied to the hex at all, like it is for all of the tiles outside my territory that I can't do anything with.  

Similarly, it doesn't seem helpful to tint mountains since it's not just that there's "Nothing to do" there's nothing that can be done -- unless maybe they could be part of a National Park but even then "Nothing to do" is not accurate and it'd be more helpful to see the potential National Park.  Right now it's just a sea of red, blending with tiles that can't be part of a National Park, possibly ever (because, for example, it's a district or city).

Along those lines, I'd find it really helpful if tiles outside of any city's working radius were indicated as such.  For me, that means if it's a bonus resource I want to harvest it or if it's a plain tile then I'm really only thinking of it in terms of an adjacency bonus (farm or forest, or maybe clearing the rainforest) not whether to improve it sooner for a worker.

It'd also be nice to highlight breathtaking coastal hexes.

Finally, it'd be nice to also have an option to turn off highlighting for all the rest of "Nothing to do".  While it is true that many of those tiles could be modified still (say, removing an improvement), it'd better focus attention on tiles that can have work done.

**Comment by astog** [comment]
> "Generic Tile" gets applied to all of flat plains, flat snow, and flat desert. When deciding whether to move a builder to a tile, it is hard to distinguish the first case, which can get a farm or forest, from the latter two, which can't have anything done to them. The same is sort of true of water with no resources, but at least you can readily tell that's what the hex is. I think my personal preference would be in all of those cases to just have no lens tint applied to the hex at all, like it is for all of the tiles outside my territory that I can't do anything with.

To clarify, you want an option that for a generic tile, no color is applied?

> Along those lines, I'd find it really helpful if tiles outside of any city's working radius were indicated as such. For me, that means if it's a bonus resource I want to harvest it or if it's a plain tile then I'm really only thinking of it in terms of an adjacency bonus (farm or forest, or maybe clearing the rainforest) not whether to improve it sooner for a worker.

This would be slightly hard to do, mainly because of the limitations of how many colors we can use. You would have noticed how colors change based on what their base is (snow vs grassland == white vs green). Hence each color has to be distinguishable regardless of the color base, which limits the color options severely. That means, if we want to show that a tile is out of cities working radius, how would you go about displaying that info.

> It'd also be nice to highlight breathtaking coastal hexes.

Reasonable request, and doable. How would you prioritize this? Above hills and forest?

> Similarly, it doesn't seem helpful to tint mountains since it's not just that there's "Nothing to do" there's nothing that can be done -- unless maybe they could be part of a National Park but even then "Nothing to do" is not accurate and it'd be more helpful to see the potential National Park. Right now it's just a sea of red, blending with tiles that can't be part of a National Park, possibly ever (because, for example, it's a district or city).
> Finally, it'd be nice to also have an option to turn off highlighting for all the rest of "Nothing to do". While it is true that many of those tiles could be modified still (say, removing an improvement), it'd better focus attention on tiles that can have work done.

My idea behind the red hex is similar to the settler lens, ie you do not want the builder to move there. But turning off the "Nothing to do", is quite simple, so I can add that as an option.

**Comment by vttale** [comment]
Responding to the very last bit first, to describe where I'm coming from:

> My idea behind the red hex is similar to the settler lens, ie you do not want the builder to move there. 

For settler I think it makes a lot of sense because you CAN'T build there.  Well, ignoring the issue with settler lens where it colours all owned territory red even when it's outside the 3 tile radius of another city, which is really noticeable as Russia which frequently has cultural expansion hit the 5 tile radius limit.

For builder, what I'd like to see is that colour draws my attention to hexes where something can be done.  Colouring hexes red is a distraction, adding information to the display about something I should be ignoring.  To my UI/UX sensibility, leaving those hexes alone is the best way to convey there is nothing to be done there.

> To clarify, you want an option that for a generic tile, no color is applied?

Well, not exactly.  I want to be able to readily distinguish a tile from where I can't do anything (flat desert or snow) from one where at least I can build a farm (flat plains).

> mainly because of the limitations of how many colors we can use

Yeah, I've been thinking palette is a bit of an issue.  I don't know enough about how the lens system works under the hood; can you only tint a tile, or could you add an icon?  Or maybe use a pattern (eg, stripe)?

As for breathtaking coastal hexes, for a resort they need to be flat so there's no conflict with hills.  As for forests, personally I'd think being coastal and breathtaking is rarer than forests in general (especially since at that point in the game where resorts are in play you can plant forests almost anywhere), so I'd say that the resort potential takes higher signalling priority.
