### ISSUE TITLE
Unimproved resources in Natural Parks marked purple in Builder Lens

### ISSUE THREAD

**Issue by vttale** [astog/MoreLenses#14]
I hesitate to call this a bug since the hex IS a resource, but for Luxury or Strategic Resources in a Natural park there isn't anything you can do about it.  I think Natural Park tiles should all have their own marking since apart from building woods in them there isn't really anything else you can do.  (Maybe you can harvest bonus resources?)  Per my other CR, my own preference would be that National Park tiles just not be tinted at all since they're basically completed work.

**Comment by vttale** [comment]
Duh .. Natural Park -> National Park.  Silly think-o.  Sorry.

**Comment by astog** [comment]
I missed that. Thank you for discovering it.
