### ISSUE TITLE
Localization error

### ISSUE THREAD

**Issue by 8h42** [astog/MoreLenses#15]
Hello astog,

I made Japanese translation, but it didn't work well.
My Database.log reported this error.

> [1607429.376] [Localization] ERROR: Database::XMLSerializer (MoreLenses_Text.xml): Duplicate column names detected in <Row>. Name: Replace, Value: 

What should I do?

![screenshot](https://cloud.githubusercontent.com/assets/11933188/24960427/bdd18bd4-1fd0-11e7-95ce-e5f3f9ff0e7a.png)

Database.log
https://www.dropbox.com/s/r8wkva3edgg2c09/Database.log?dl=0

MoreLenses_Text.xml
https://www.dropbox.com/s/fcd6jqu1inioyod/MoreLenses_Text.xml?dl=0

**Comment by astog** [comment]
I can see a syntax error in line 206 with a missing < . Try fixing that and see what happens.

**Comment by 8h42** [comment]
Oops!
Thank you for pointing it out.
Now it works fine.
Here is a Japanese translation file for the More Lenses 2.0.
It would be great if you could incorporate it in a future update.
http://www.dropbox.com/s/8wt9aget20zoj7k/MoreLenses_Text_ja.xml?dl=0

**Comment by astog** [comment]
Added in 5c36b8d72bc7b1c604dfc5a43c9ee83127df06ad
