### ISSUE TITLE
unclear docs?, potential bug?

### ISSUE THREAD

**Issue by ahnbizcad** [astog/MoreLenses#16]
When you say "Delete MinimapPanel.lua and MinimapPanel.xml from CQUI",
do you mean delete it from the original Chao QUI? It should have to be that one, since I'm guessing MoreLenses has its own settings in MinimapPanel.lua and MinimapPanel.xml

In Chao QUI, the file names are minimappanel.lua and minimappanel.xml, not capitalized.
I'm not sure if that matters or not.

Anyway, I deleted them from Chao QUI, and kept the ones from MoreLenses, but I am still getting bugs.
The Chao QUI options icon is there, but the menu doesn't show up.

Did I delete the wrong one? Am I supposed to delete the one from MoreLenses?
If so, then it would be good to make the documentation wording more clear to something like,

"Delete MinimapPanel.lua and MinimapPanel.xml from MoreLenses".

Thanks for all the work you put into this. This is one of my favorite mods.

**Comment by astog** [comment]
Since this is mod is now included within CQUI, this mod requires no extra steps if using CQUI. Thank you for pointing this out. Will be fixed in an upcoming commit.
