### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by Ludicrous2k** [astog/MoreLenses#18]
Seeing the below on the newest release version (v2). Not sure if i'm the only one. I'm on 1.0.0.129 (260180)

Runtime Error: D:\Steam\Sid Meiers Civilization VI\DLC\MoreLenses\UI\MinimapPanel.lua:3360: function expected instead of nil
stack traceback:
	D:\Steam\Sid Meiers Civilization VI\DLC\MoreLenses\UI\MinimapPanel.lua:3360: in function 'Initialize'
	D:\Steam\Sid Meiers Civilization VI\DLC\MoreLenses\UI\MinimapPanel.lua:3464: in function '(main chunk)'
	[C]: in function '(anonymous)'
Lua callstack:
Runtime Error: Error loading D:\Steam\Sid Meiers Civilization VI\DLC\MoreLenses\UI\MinimapPanel.lua.
stack traceback:
	[C]: in function '(anonymous)'

**Comment by astog** [comment]
That refers to this line of code 

```lua
 Controls.MinimapImage:RegisterSizeChanged( OnMinimapImageSizeChanged );
```

This was added in the summer update. Are you running this mod in linux or mac? Or possibly, you don't have the latest update?

**Comment by Ludicrous2k** [comment]
Hmm...possible i dont have the latest update

**Comment by Ludicrous2k** [comment]
Just tested, sorry my fault i thought it was up to date
