### ISSUE TITLE
Builder Lens

### ISSUE THREAD

**Issue by dirthsj** [astog/MoreLenses#23]
Please consider indicating which tiles are not workable when the builder lens is selected.

**Comment by astog** [comment]
I had them before but ran into an issue of having too many tiles late game being red. Right now I highlight unworkable tiles only if either we don't have the technology / governor to do something, or there is no improvement possible on that tile. If you have a district or a improvement I do no highlighting those dominate late game tiles and highlighting them seems unnecessary.

**Comment by KingofGamesYami** [comment]
If nothing else, I would recommend not highlighting resources that can't be worked purple.  Highlight them as aqua to designate them as a lower priority than resources which can be worked.

**Comment by astog** [comment]
Integrated this with the Gathering storm update.
