### ISSUE TITLE
All Lens View Break in Gathering Storm

### ISSUE THREAD

**Issue by quill18** [astog/MoreLenses#27]
This issue is expected, but with this mod enabled, all lens views stop working in Gathering Storm (press preview).

What kind of debug info can I provide you to get a jump on this for release?

**Comment by astog** [comment]
I just bought the GS expansion, so I will get to work patching my mods.

**Comment by Sheetka** [comment]
can't wait for the update! definetely the most useful mod out there

**Comment by astog** [comment]
Should be resolved with the Gathering Storm Release [v4.0](https://github.com/astog/MoreLenses/releases/tag/4.0)
