### ISSUE TITLE
Archaeologist Lens will not be successfully selected automatically

### ISSUE THREAD

**Issue by raki-can** [astog/MoreLenses#28]
The lens itself is functioning properly, but the lens does not become effective even if you select the archaeologist unit.
![lens-001](https://user-images.githubusercontent.com/41435700/53474296-0b50a380-3ab0-11e9-933f-b1c9b7b9736e.jpg)

Builder lenses are functioning properly.
![lens-002](https://user-images.githubusercontent.com/41435700/53474358-34713400-3ab0-11e9-8afa-78f49eb15c02.jpg)

**Comment by astog** [comment]
Since the base game now applies a lens for archaeologists, I felt automatically applying my version of it would be too much. I kept the lens available on the menu, since that was one way to finding dig sites (until the recent map search feature). Hope this answers you question :)
