### ISSUE TITLE
Builder Lens doesn't support Hotseat Multiplayer

### ISSUE THREAD

**Issue by ubereffect** [astog/MoreLenses#30]
How to test:
Start a hotseat multiplayer game, setting the first 3 players as human (first 2 humans in a team, 3rd one solo), and the last player(s) occupied by computer(s). A duel sized pangaea probably works best for this.

What happens:
The Builder Lens only works as expected for player 1. As for players 2 & 3, the Builder Lens darkens all their owned tiles. Interestingly, when player 2 uses the Builder lens, it highlights improvable tiles owned by player 1 (as they have shared visibility), but does not highlight it's own improvable tiles.

If you start a fresh game, it only works for player 1. But if you then save it when it's another players turn, and reload the game from that point, it will only work for that player going forward (and won't work for player 1).

- OS: Windows 10
- Version: 1.0.0.290
- Expansions: All expansions and DLC, including Rise & Fall, and Gathering Storm
- Other mods: None

I should also note that I played a number of hotseat multiplayer games with CQUI enabled prior to Gathering Storm, and this issue was not present until this recent update. Issue present in both the stand alone mod and in CQUI, since Gathering Storm update.

**Comment by astog** [comment]
Fixed in 926e86bf5410b0cdd474adf107bd6a2982d28658
