### ISSUE TITLE
Add Localized text for other languages

### ISSUE THREAD

**Issue by astog** [astog/MoreLenses#5]
Add localized text for the remaining languages. Any help would be appreciated with this. Fall back option is to use Google Translate.

**Comment by Serpens66** [comment]
german translation:

<?xml version="1.0" encoding="utf-8"?>
<GameData>
  <LocalizedText>
    

    
    <Replace Tag="LOC_HUD_BUILDER_LENS" Language="de_DE">
      <Text>Handwerker</Text>
    </Replace>
    <Replace Tag="LOC_HUD_BUILDER_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt besondere Felder auf der Karte an, wo gebaut werden kann.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_BUILDER_LENS_IMP" Language="de_DE">
      <Text>Ressource/Geplündert/Einzigartig</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RECOMFEATURE_LENS_HILL" Language="de_DE">
      <Text>Empfohlenes Feature zum verbessern</Text>
    </Replace>    
    <Replace Tag="LOC_TOOLTIP_BUILDER_LENS_HILL" Language="de_DE">
      <Text>Hügel</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_BUILDER_LENS_FEATURE" Language="de_DE">
      <Text>Entfernbares Feature</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_BUILDER_LENS_GENERIC" Language="de_DE">
      <Text>Normales Feld</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_BUILDER_LENS_NOTHING" Language="de_DE">
      <Text>Nichts zu tun</Text>
    </Replace>

    
    <Replace Tag="LOC_HUD_ARCHAEOLOGIST_LENS" Language="de_DE">
      <Text>Archäologe</Text>
    </Replace>
    <Replace Tag="LOC_HUD_ARCHAEOLOGIST_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt Ausgrabungsstätten auf der Karte.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_ARCHAEOLOGIST_LENS_ARTIFACT" Language="de_DE">
      <Text>Artefakt</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_ARCHAEOLOGIST_LENS_SHIPWRECK" Language="de_DE">
      <Text>Schiffswrack</Text>
    </Replace>

    
    
    <Replace Tag="LOC_HUD_CITYOVERLAP_LENS" Language="de_DE">
      <Text>Neue Stadt</Text>
    </Replace>
    <Replace Tag="LOC_HUD_CITYOVERLAP_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt wieviele Städte (innerhalb von 6 Hexfeldern) mit dem Feld überlappen</Text>
    </Replace>
    <Replace Tag="LOC_PANEL_CITYOVERLAP_OPTION1" Language="de_DE">
      <Text>Zeigt ausserhalb Grenzen</Text>
    </Replace>
    <Replace Tag="LOC_PANEL_CITYOVERLAP_NMOUSE" Language="de_DE">
      <Text>Keine Maus</Text>
    </Replace>
    <Replace Tag="LOC_PANEL_CITYOVERLAP_RANGE" Language="de_DE">
      <Text>Maus Reichweite</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_CITYOVERLAP_RANGE" Language="de_DE">
      <Text>Zeigt Felder und markiert Städte in Reichweite (Einstellung unten) des Feldes unter der Maus</Text>
    </Replace>
    <Replace Tag="LOC_PANEL_CITYOVERLAP_RADIUS" Language="de_DE">
      <Text>Maus Radius</Text>
    </Replace>

    
    <Replace Tag="LOC_HUD_BARBARIAN_LENS" Language="de_DE">
      <Text>Barbaren</Text>
    </Replace>
    <Replace Tag="LOC_HUD_BARBARIAN_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt Barbaren-Außenposten auf der Karte.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_BARBARIAN_LENS_ENCAPMENT" Language="de_DE">
      <Text>Barbaren- Außenposten</Text>
    </Replace>

    
    <Replace Tag="LOC_HUD_RESOURCE_LENS" Language="de_DE">
      <Text>Ressourcen</Text>
    </Replace>
    <Replace Tag="LOC_HUD_RESOURCE_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt Ressourcenfelder.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RESOURCE_LENS_LUXURY" Language="de_DE">
      <Text>Luxusressource</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RESOURCE_LENS_NLUXURY" Language="de_DE">
      <Text>Unerschlossene Luxusressource</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RESOURCE_LENS_STRATEGIC" Language="de_DE">
      <Text>Strategische Ressource</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RESOURCE_LENS_NSTRATEGIC" Language="de_DE">
      <Text>Unerschlossene strateg. Ressource</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RESOURCE_LENS_BONUS" Language="de_DE">
      <Text>Bonusressource</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RESOURCE_LENS_NBONUS" Language="de_DE">
      <Text>Unerschlossene Bonusressource</Text>
    </Replace>

    
    <Replace Tag="LOC_HUD_WONDER_LENS" Language="de_DE">
      <Text>Wunder</Text>
    </Replace>
    <Replace Tag="LOC_HUD_WONDER_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt Naturwunder und gebaute Wunder auf der Karte.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_WONDER_LENS_NWONDER" Language="de_DE">
      <Text>Naturwunder</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_RESOURCE_LENS_PWONDER" Language="de_DE">
      <Text>Gebaute Wunder</Text>
    </Replace>

    
    <Replace Tag="LOC_HUD_ADJYIELD_LENS" Language="de_DE">
      <Text>Nachbarerträge</Text>
    </Replace>
    <Replace Tag="LOC_HUD_ADJYIELD_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt die Nachbarschaftserträge der Bezirke.</Text>
    </Replace>

    
    <Replace Tag="LOC_HUD_SCOUT_LENS" Language="de_DE">
      <Text>Späher</Text>
    </Replace>
    <Replace Tag="LOC_HUD_SCOUT_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt Stammesdörfer auf der Karte.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_SCOUT_LENS_GHUT" Language="de_DE">
      <Text>Stammesdorf</Text>
    </Replace>

    
    <Replace Tag="LOC_HUD_NATURALIST_LENS" Language="de_DE">
      <Text>Naturalist</Text>
    </Replace>
    <Replace Tag="LOC_HUD_NATURALIST_LENS_TOOLTIP" Language="de_DE">
      <Text>Zeigt Felder auf denen Nationalparks gebaut werden können.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_NATURALIST_LENS_NPARK" Language="de_DE">
      <Text>Gebiet ist bereit für einen Nationalpark.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_NATURALIST_LENS_OK" Language="de_DE">
      <Text>Feld könnte genutzt werden, sobald ein anderes Feld verändert wurde.</Text>
    </Replace>
    <Replace Tag="LOC_TOOLTIP_NATURALIST_LENS_FIXABLE" Language="de_DE">
      <Text>Muss verändert werden, um für einen Nationalpark genutzt werden zu können.</Text>
    </Replace>

  </LocalizedText>
</GameData>
